export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const GET_BUSINESSES = "GET_BUSINESSES";
export const GET_BUSINESS_INFO = "GET_BUSINESS_INFO";
export const GET_FORM_INFO = "GET_FORM_INFO";
export const GET_FORM_SUBMISSIONS = "GET_FORM_SUBMISSIONS";
export const GET_FORM_SUBMISSIONS_DETAIL = "GET_FORM_SUBMISSIONS_DETAIL";
